import type { Metadata } from "next";
import { LegalPage } from "../../components/legal/LegalPage";

export const metadata: Metadata = {
  title: "Privacy Policy — Veira",
  description: "What Veira collects, why, and how to get your data removed.",
};

const content = {
  tr: {
    heading: "Gizlilik Politikası",
    updated: "Son güncelleme: 30 Eylül 2026",
    sections: [
      {
        h: "Ne topluyoruz",
        p: [
          "Hesap oluşturduğunda: e-posta adresin ve (e-posta ile kayıt olduysan) şifren, ya da Google ile giriş yaptıysan Google hesabından paylaştığın ad, e-posta ve profil fotoğrafı.",
          "Profilinde kendi eklediğin bilgiler: kullanıcı adı, cinsiyet, uyruk, telefon, boy ve kilo gibi alanlar — bunların hiçbiri zorunlu değildir, sadece doldurduğun kadarı saklanır.",
          "Uygulama kullanımından doğan veriler: koştuğun toplam kilometre, kayıtlı ayakkabı sayısı, kayıt olduğun yarışlar ve üye olduğun koşu kulüpleri.",
        ],
      },
      {
        h: "Bunları ne için kullanıyoruz",
        p: [
          "Hesabını çalıştırmak, haftalık lig sıralamanı ve profilini göstermek için.",
          "Kulüp özelliklerinde, üyesi olduğun kulüpteki diğer kullanıcılara kullanıcı adın ve profilin görünür — bunun dışında profilin herkese açık değildir.",
          "Reklam amaçlı takip veya üçüncü taraf reklam ağlarıyla veri paylaşımı yapmıyoruz.",
        ],
      },
      {
        h: "Nerede saklanıyor",
        p: [
          "Verilerin Supabase altyapısında (yönetilen Postgres veritabanı) tutulur. Google ile giriş yaptıysan, kimlik doğrulaması için Google'ın kendi servisleri de devreye girer — bu durumda Google'ın kendi gizlilik politikası da geçerlidir.",
        ],
      },
      {
        h: "Çerezler ve yerel depolama",
        p: [
          "Oturumunu açık tutmak, dil ve tema tercihini hatırlamak için tarayıcının yerel depolamasını (localStorage) kullanıyoruz. Reklam amaçlı üçüncü taraf takip çerezi kullanmıyoruz.",
        ],
      },
      {
        h: "Verilerin üzerindeki hakların",
        p: [
          "Profilindeki bilgileri istediğin zaman profil sayfandan düzenleyebilirsin. Hesabını ve verilerini tamamen silmek istersen bizimle iletişime geçmen yeterli — talebini en kısa sürede işleme alırız.",
        ],
      },
      {
        h: "Değişiklikler",
        p: ["Bu politikayı zaman zaman güncelleyebiliriz; önemli değişiklikleri bu sayfada yayınlayarak duyururuz."],
      },
      {
        h: "İletişim",
        p: ["Sorular için: privacy@appveira.com"],
      },
    ],
  },
  en: {
    heading: "Privacy Policy",
    updated: "Last updated: September 30, 2026",
    sections: [
      {
        h: "What we collect",
        p: [
          "When you create an account: your email address and (if you signed up with email) your password, or — if you signed in with Google — the name, email and profile photo Google shares with us.",
          "Whatever you choose to add to your profile: username, gender, nationality, phone, height and weight. None of these are required; we only store what you actually fill in.",
          "Data generated by using the app: your total kilometers run, tracked shoe count, races you've registered interest in, and running clubs you've joined.",
        ],
      },
      {
        h: "What we use it for",
        p: [
          "To run your account, show your weekly league position and your profile.",
          "Inside club features, your username and profile are visible to other members of clubs you've joined — otherwise your profile isn't public.",
          "We don't do ad tracking or share your data with third-party ad networks.",
        ],
      },
      {
        h: "Where it lives",
        p: [
          "Your data is stored on Supabase's infrastructure (a managed Postgres database). If you sign in with Google, Google's own services are involved in authentication, and Google's own privacy policy applies to that part.",
        ],
      },
      {
        h: "Cookies & local storage",
        p: [
          "We use your browser's local storage to keep you signed in and remember your language and theme preference. We don't use third-party ad-tracking cookies.",
        ],
      },
      {
        h: "Your rights over your data",
        p: [
          "You can edit the information on your profile at any time from your profile page. If you want your account and data deleted entirely, just get in touch — we'll process the request promptly.",
        ],
      },
      {
        h: "Changes",
        p: ["We may update this policy from time to time; material changes will be posted on this page."],
      },
      {
        h: "Contact",
        p: ["Questions: privacy@appveira.com"],
      },
    ],
  },
  es: {
    heading: "Política de Privacidad",
    updated: "Última actualización: 30 de septiembre de 2026",
    sections: [
      {
        h: "Qué recopilamos",
        p: [
          "Al crear una cuenta: tu correo electrónico y (si te registraste con correo) tu contraseña, o — si iniciaste sesión con Google — el nombre, correo y foto de perfil que Google nos comparte.",
          "Lo que decidas añadir a tu perfil: nombre de usuario, género, nacionalidad, teléfono, altura y peso. Ninguno de estos campos es obligatorio; solo guardamos lo que realmente completes.",
          "Datos generados por el uso de la app: los kilómetros totales que has corrido, el número de zapatillas registradas, las carreras en las que muestras interés y los clubes de running a los que te unes.",
        ],
      },
      {
        h: "Para qué lo usamos",
        p: [
          "Para gestionar tu cuenta y mostrar tu posición en la liga semanal y tu perfil.",
          "Dentro de las funciones de clubes, tu nombre de usuario y perfil son visibles para otros miembros de los clubes a los que te unes — fuera de eso, tu perfil no es público.",
          "No hacemos seguimiento publicitario ni compartimos tus datos con redes publicitarias de terceros.",
        ],
      },
      {
        h: "Dónde se almacena",
        p: [
          "Tus datos se almacenan en la infraestructura de Supabase (una base de datos Postgres gestionada). Si inicias sesión con Google, los propios servicios de Google intervienen en la autenticación, y la política de privacidad de Google se aplica a esa parte.",
        ],
      },
      {
        h: "Cookies y almacenamiento local",
        p: [
          "Usamos el almacenamiento local de tu navegador para mantener tu sesión iniciada y recordar tu idioma y preferencia de tema. No usamos cookies publicitarias de terceros.",
        ],
      },
      {
        h: "Tus derechos sobre tus datos",
        p: [
          "Puedes editar la información de tu perfil en cualquier momento desde tu página de perfil. Si quieres que eliminemos tu cuenta y tus datos por completo, simplemente contáctanos — procesaremos la solicitud lo antes posible.",
        ],
      },
      {
        h: "Cambios",
        p: ["Podemos actualizar esta política de vez en cuando; los cambios importantes se publicarán en esta página."],
      },
      {
        h: "Contacto",
        p: ["Preguntas: privacy@appveira.com"],
      },
    ],
  },
};

export default function PrivacyPage() {
  return <LegalPage content={content} />;
}
